"""Build a reproducible manifest for the raw CardioVUS data files.

Output
------
data/data_manifest.csv

Usage
-----
Run from the repository root:

    python src/cardiovus/data/build_data_manifest.py
"""

from __future__ import annotations

import csv
import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parents[3]
MANIFEST_PATH = ROOT_DIR / "data" / "data_manifest.csv"


# ---------------------------------------------------------------------
# Expected raw files
# ---------------------------------------------------------------------

DATA_FILES = [
    {
        "source": "MaveDB",
        "source_identifier": "urn:mavedb:00001231-a-2",
        "file_role": "Score-set metadata",
        "relative_path": "data/raw/mavedb/score_set_metadata.json",
        "source_url": (
            "https://api.mavedb.org/api/v1/"
            "score-sets/urn:mavedb:00001231-a-2"
        ),
    },
    {
        "source": "MaveDB",
        "source_identifier": "urn:mavedb:00001231-a-2",
        "file_role": "Experimental variant scores",
        "relative_path": "data/raw/mavedb/scores.csv",
        "source_url": (
            "https://api.mavedb.org/api/v1/"
            "score-sets/urn:mavedb:00001231-a-2/scores"
        ),
    },
    {
        "source": "MaveDB",
        "source_identifier": "urn:mavedb:00001231-a-2",
        "file_role": "Mapped variants",
        "relative_path": "data/raw/mavedb/mapped_variants.json",
        "source_url": (
            "https://api.mavedb.org/api/v1/"
            "score-sets/urn:mavedb:00001231-a-2/mapped-variants"
        ),
    },
    {
        "source": "NCBI RefSeq",
        "source_identifier": "NP_000229.1",
        "file_role": "Reference protein sequence",
        "relative_path": "data/raw/reference/NP_000229.1.fasta",
        "source_url": (
            "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
            "efetch.fcgi?db=protein&id=NP_000229.1"
            "&rettype=fasta&retmode=text"
        ),
    },
    {
        "source": "NCBI RefSeq",
        "source_identifier": "NP_000229.1",
        "file_role": "Annotated GenPept record",
        "relative_path": "data/raw/reference/NP_000229.1.gp",
        "source_url": (
            "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
            "efetch.fcgi?db=protein&id=NP_000229.1"
            "&rettype=gp&retmode=text"
        ),
    },
    {
        "source": "NCBI RefSeq",
        "source_identifier": "NP_000229.1",
        "file_role": "Locally generated reference metadata",
        "relative_path": (
            "data/raw/reference/NP_000229.1_metadata.json"
        ),
        "source_url": "Generated by download_reference.py",
    },
]


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------

def calculate_sha256(file_path: Path) -> str:
    """Calculate the SHA-256 checksum of a file."""
    digest = hashlib.sha256()

    with file_path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)

    return digest.hexdigest()


def file_timestamp_utc(file_path: Path) -> str:
    """Return the local file modification time in UTC."""
    timestamp = file_path.stat().st_mtime

    return datetime.fromtimestamp(
        timestamp,
        tz=timezone.utc,
    ).isoformat()


# ---------------------------------------------------------------------
# Manifest generation
# ---------------------------------------------------------------------

def build_manifest() -> None:
    """Validate the expected files and create the manifest."""
    missing_files: list[Path] = []
    rows: list[dict[str, str | int]] = []

    for specification in DATA_FILES:
        file_path = ROOT_DIR / specification["relative_path"]

        if not file_path.exists():
            missing_files.append(file_path)
            continue

        rows.append(
            {
                "source": specification["source"],
                "source_identifier": specification[
                    "source_identifier"
                ],
                "file_role": specification["file_role"],
                "relative_path": specification["relative_path"],
                "file_format": file_path.suffix.lstrip("."),
                "size_bytes": file_path.stat().st_size,
                "sha256": calculate_sha256(file_path),
                "local_file_timestamp_utc": file_timestamp_utc(
                    file_path
                ),
                "source_url": specification["source_url"],
            }
        )

    if missing_files:
        missing_text = "\n".join(
            f"  - {path}" for path in missing_files
        )

        raise FileNotFoundError(
            "The manifest could not be generated because these "
            f"files are missing:\n{missing_text}"
        )

    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "source",
        "source_identifier",
        "file_role",
        "relative_path",
        "file_format",
        "size_bytes",
        "sha256",
        "local_file_timestamp_utc",
        "source_url",
    ]

    with MANIFEST_PATH.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print("=" * 72)
    print("Data manifest generated successfully")
    print("=" * 72)
    print(f"Output: {MANIFEST_PATH}")
    print(f"Files documented: {len(rows)}")

    for row in rows:
        print(
            f"- {row['relative_path']} "
            f"({row['size_bytes']:,} bytes)"
        )


def main() -> int:
    """Run manifest generation."""
    try:
        build_manifest()
    except (OSError, FileNotFoundError) as error:
        print(f"\n[ERROR] {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

{
    "source": "UniProtKB",
    "source_identifier": "Q12809",
    "file_role": "Curated UniProtKB JSON entry",
    "relative_path": "data/raw/uniprot/Q12809.json",
    "source_url": (
        "https://rest.uniprot.org/uniprotkb/Q12809.json"
    ),
},
{
    "source": "UniProtKB",
    "source_identifier": "Q12809",
    "file_role": "Curated sequence features in GFF",
    "relative_path": "data/raw/uniprot/Q12809.gff",
    "source_url": (
        "https://rest.uniprot.org/uniprotkb/Q12809.gff"
    ),
},
{
    "source": "UniProtKB",
    "source_identifier": "Q12809",
    "file_role": "Locally generated download metadata",
    "relative_path": (
        "data/raw/uniprot/"
        "Q12809_download_metadata.json"
    ),
    "source_url": (
        "Generated by "
        "download_uniprot_features.py"
    ),
},
{
    "source": "UniProtKB",
    "source_identifier": "Q12809",
    "file_role": "Normalized sequence features",
    "relative_path": (
        "data/external/"
        "kcnh2_uniprot_features.csv"
    ),
    "source_url": (
        "Derived from Q12809.json by "
        "download_uniprot_features.py"
    ),
},
{
    "source": "UniProtKB",
    "source_identifier": "Q12809",
    "file_role": "Domain analysis annotations",
    "relative_path": (
        "data/external/"
        "kcnh2_domains.csv"
    ),
    "source_url": (
        "Derived from Q12809.json by "
        "download_uniprot_features.py"
    ),
},